### ISSUE TITLE
After press floatingActionButton 

### ISSUE THREAD

**Issue by Shoyadbek** [i-Naji/tdlib#12]
Hi Sir. 

After pressing floatingActionButton (_clientCreator) my app is crashed. Please help me

`Launching lib/main.dart on Android SDK built for x86 in debug mode...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:60432/lwjmrRocakQ=/ws
D/EGL_emulation(20174): eglMakeCurrent: 0xb0464be0: ver 3 0 (tinfo 0xa5b7f7e0)
E/zygote  (20174): No implementation found for long org.drinkless.tdlib.JsonClient.create() (tried Java_org_drinkless_tdlib_JsonClient_create and Java_org_drinkless_tdlib_JsonClient_create__)
E/flutter (20174): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.UnsatisfiedLinkError: No implementation found for long org.drinkless.tdlib.JsonClient.create() (tried Java_org_drinkless_tdlib_JsonClient_create and Java_org_drinkless_tdlib_JsonClient_create__)
E/flutter (20174): 	at org.drinkless.tdlib.JsonClient.create(Native Method)
E/flutter (20174): 	at org.naji.td.tdlib.TdlibPlugin.onMethodCall(TdlibPlugin.java:38)
E/flutter (20174): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/flutter (20174): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (20174): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/flutter (20174): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (20174): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/flutter (20174): 	at android.os.Looper.loop(Looper.java:142)
E/flutter (20174): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/flutter (20174): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (20174): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/flutter (20174): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/flutter (20174):
F/flutter (20174): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).
F/libc    (20174): Fatal signal 6 (SIGABRT), code -6 in tid 20174 (e.hello_flutter), pid 20174 (e.hello_flutter)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:8.1.0/OSM1.180201.007/4586646:user/release-keys'
Revision: '0'
ABI: 'x86'
pid: 20174, tid: 20174, name: e.hello_flutter  >>> com.example.hello_flutter <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).
'
    eax 00000000  ebx 00004ece  ecx 00004ece  edx 00000006
    esi b042b1b0  edi 00004ece
    xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
    eip b4c3dac4  ebp bf97a7d8  esp bf97a768  flags 00200286
backtrace:
    #00 pc 00000ac4  [vdso:b4c3d000] (__kernel_vsyscall+16)
    #01 pc 0001edf8  /system/lib/libc.so (syscall+40)
    #02 pc 0001f073  /system/lib/libc.so (abort+115)
    #03 pc 011c5cb1  /data/app/com.example.hello_flutter-ZgwdxMbtgzKhSWdi9d4y_A==/lib/x86/libflutter.so (offset 0x11a9000)
    #04 pc 011b26e7  /data/app/com.example.hello_flutter-ZgwdxMbtgzKhSWdi9d4y_A==/lib/x86/libflutter.so (offset 0x11a9000)
    #05 pc 011b0480  /data/app/com.example.hello_flutter-ZgwdxMbtgzKhSWdi9d4y_A==/lib/x86/libflutter.so (offset 0x11a9000)
    #06 pc 01219191  /data/app/com.example.hello_flutter-ZgwdxMbtgzKhSWdi9d4y_A==/lib/x86/libflutter.so (offset 0x11a9000)
    #07 pc 011c40c3  /data/app/com.example.hello_flutter-ZgwdxMbtgzKhSWdi9d4y_A==/lib/x86/libflutter.so (offset 0x11a9000)
    #08 pc 011c6a09  /data/app/com.example.hello_flutter-ZgwdxMbtgzKhSWdi9d4y_A==/lib/x86/libflutter.so (offset 0x11a9000)
    #09 pc 011c694e  /data/app/com.example.hello_flutter-ZgwdxMbtgzKhSWdi9d4y_A==/lib/x86/libflutter.so (offset 0x11a9000)
    #10 pc 011ccb5a  /data/app/com.example.hello_flutter-ZgwdxMbtgzKhSWdi9d4y_A==/lib/x86/libflutter.so (offset 0x11a9000)
    #11 pc 011ccb88  /data/app/com.example.hello_flutter-ZgwdxMbtgzKhSWdi9d4y_A==/lib/x86/libflutter.so (offset 0x11a9000)
    #12 pc 00014af7  /system/lib/libutils.so (android::SimpleLooperCallback::handleEvent(int, int, void*)+39)
    #13 pc 00015936  /system/lib/libutils.so (android::Looper::pollInner(int)+982)
    #14 pc 000154d6  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+118)
    #15 pc 000e25cb  /system/lib/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long long, int)+59)
    #16 pc 007d5428  /system/framework/x86/boot-framework.oat (offset 0x606000) (android.app.NativeActivity.onWindowFocusChangedNative [DEDUPED]+136)
    #17 pc 00002d4e  /dev/ashmem/dalvik-jit-code-cache (deleted)
Lost connection to device.
Exited (sigterm)
`

**Comment by nehastu** [comment]
My solution was to move the code below from **TdlibPlugin** to **JsonClient** class.

```
static {
     try {
         System.loadLibrary("tdjson");
         Log.i("TDLib", "TDJson loaded");
     } catch (UnsatisfiedLinkError e) {
         Log.w("TDLib", "Can't load TDJson", e);
     }
 }
```

also If you are using emulators, make sure that you use _**x86_64**_, _**armeabi-v7a**_, or _**arm64-v8a**_ system image.
