### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by GavinToHill** [i-Naji/tdlib#20]
![image](https://user-images.githubusercontent.com/49137054/93294726-636b0a00-f7fc-11ea-9585-fa5e83a178a9.png)

**Comment by i-Naji** [comment]
you got any error while compiling?

**Comment by GavinToHill** [comment]
yes, it recommend me add ignore, then it is ok
![image](https://user-images.githubusercontent.com/49137054/93310847-5824d800-f816-11ea-88bd-d1ce596a6a08.png)
