### ISSUE TITLE
Hot restarting the example gives TDLib error.

### ISSUE THREAD

**Issue by iamcosmin** [i-Naji/tdlib#25]
When the example is hot restarted, I receive the following TDLib error:
`E/EventChannel#channel/to/tdlib/receive(19857): Failed to close existing event stream
E/EventChannel#channel/to/tdlib/receive(19857): java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Number.longValue()' on a null object reference
E/EventChannel#channel/to/tdlib/receive(19857): 	at org.naji.td.tdlib.TdlibPlugin.onCancel(TdlibPlugin.java:175)
E/EventChannel#channel/to/tdlib/receive(19857): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:182)
E/EventChannel#channel/to/tdlib/receive(19857): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:167)
E/EventChannel#channel/to/tdlib/receive(19857): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/EventChannel#channel/to/tdlib/receive(19857): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/EventChannel#channel/to/tdlib/receive(19857): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/EventChannel#channel/to/tdlib/receive(19857): 	at android.os.MessageQueue.next(MessageQueue.java:336)
`

**Comment by i-Naji** [comment]
#22
