### ISSUE TITLE
Failed to close existing event stream

### ISSUE THREAD

**Issue by alazarLaz** [i-Naji/tdlib#28]
This is not the result of hot reload,

Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
 lib/main.dart
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:37311/7dYhxWJixZc=/ws
D/EGL_emulation( 6459): eglMakeCurrent: 0x7cc65b7310a0: ver 2 0 (tinfo 0x7cc653866880)
I/DLTD    ( 6459): [ 3][t 4][1606299166.683610200][Td.cpp:4490][#1][!Td][&td_requests]	Sending update: updateOption {
I/DLTD    ( 6459):   name = "version"
I/DLTD    ( 6459):   value = optionValueString {
I/DLTD    ( 6459):     value = "1.6.8"
I/DLTD    ( 6459):   }
I/DLTD    ( 6459): }
I/DLTD    ( 6459): [ 3][t 4][1606299166.683663129][Td.cpp:4490][#1][!Td][&td_requests]	Sending update: updateAuthorizationState {
I/DLTD    ( 6459):   authorization_state = authorizationStateWaitTdlibParameters {
I/DLTD    ( 6459):   }
I/DLTD    ( 6459): }
I/DLTD    ( 6459): [ 3][t 7][1606299166.891062021][Td.cpp:4490][#2][!Td][&td_requests]	Sending update: updateOption {
I/DLTD    ( 6459):   name = "version"
I/DLTD    ( 6459):   value = optionValueString {
I/DLTD    ( 6459):     value = "1.6.8"
I/DLTD    ( 6459):   }
I/DLTD    ( 6459): }
I/DLTD    ( 6459): [ 3][t 7][1606299166.891098260][Td.cpp:4490][#2][!Td][&td_requests]	Sending update: updateAuthorizationState {
I/DLTD    ( 6459):   authorization_state = authorizationStateWaitTdlibParameters {
I/DLTD    ( 6459):   }
I/DLTD    ( 6459): }
E/EventChannel#channel/to/tdlib/receive( 6459): Failed to close existing event stream
E/EventChannel#channel/to/tdlib/receive( 6459): java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Number.longValue()' on a null object reference
E/EventChannel#channel/to/tdlib/receive( 6459): 	at org.naji.td.tdlib.TdlibPlugin.onCancel(TdlibPlugin.java:175)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:182)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:167)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at android.os.Looper.loop(Looper.java:136)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
E/EventChannel#channel/to/tdlib/receive( 6459): Failed to close existing event stream
E/EventChannel#channel/to/tdlib/receive( 6459): java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Number.longValue()' on a null object reference
E/EventChannel#channel/to/tdlib/receive( 6459): 	at org.naji.td.tdlib.TdlibPlugin.onCancel(TdlibPlugin.java:175)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:182)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:167)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at android.os.Looper.loop(Looper.java:136)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
E/EventChannel#channel/to/tdlib/receive( 6459): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by alazarLaz** [comment]
> This is not the result of hot reload,
> 
> Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
> lib/main.dart
> ✓ Built build/app/outputs/flutter-apk/app-debug.apk.
> Connecting to VM Service at ws://127.0.0.1:37311/7dYhxWJixZc=/ws
> D/EGL_emulation( 6459): eglMakeCurrent: 0x7cc65b7310a0: ver 2 0 (tinfo 0x7cc653866880)
> I/DLTD ( 6459): [ 3][t 4][1606299166.683610200][Td.cpp:4490][#1][!Td][&td_requests] Sending update: updateOption {
> I/DLTD ( 6459): name = "version"
> I/DLTD ( 6459): value = optionValueString {
> I/DLTD ( 6459): value = "1.6.8"
> I/DLTD ( 6459): }
> I/DLTD ( 6459): }
> I/DLTD ( 6459): [ 3][t 4][1606299166.683663129][Td.cpp:4490][#1][!Td][&td_requests] Sending update: updateAuthorizationState {
> I/DLTD ( 6459): authorization_state = authorizationStateWaitTdlibParameters {
> I/DLTD ( 6459): }
> I/DLTD ( 6459): }
> I/DLTD ( 6459): [ 3][t 7][1606299166.891062021][Td.cpp:4490][#2][!Td][&td_requests] Sending update: updateOption {
> I/DLTD ( 6459): name = "version"
> I/DLTD ( 6459): value = optionValueString {
> I/DLTD ( 6459): value = "1.6.8"
> I/DLTD ( 6459): }
> I/DLTD ( 6459): }
> I/DLTD ( 6459): [ 3][t 7][1606299166.891098260][Td.cpp:4490][#2][!Td][&td_requests] Sending update: updateAuthorizationState {
> I/DLTD ( 6459): authorization_state = authorizationStateWaitTdlibParameters {
> I/DLTD ( 6459): }
> I/DLTD ( 6459): }
> E/EventChannel#channel/to/tdlib/receive( 6459): Failed to close existing event stream
> E/EventChannel#channel/to/tdlib/receive( 6459): java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Number.longValue()' on a null object reference
> E/EventChannel#channel/to/tdlib/receive( 6459): at org.naji.td.tdlib.TdlibPlugin.onCancel(TdlibPlugin.java:175)
> E/EventChannel#channel/to/tdlib/receive( 6459): at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:182)
> E/EventChannel#channel/to/tdlib/receive( 6459): at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:167)
> E/EventChannel#channel/to/tdlib/receive( 6459): at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
> E/EventChannel#channel/to/tdlib/receive( 6459): at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
> E/EventChannel#channel/to/tdlib/receive( 6459): at android.os.MessageQueue.nativePollOnce(Native Method)
> E/EventChannel#channel/to/tdlib/receive( 6459): at android.os.MessageQueue.next(MessageQueue.java:323)
> E/EventChannel#channel/to/tdlib/receive( 6459): at android.os.Looper.loop(Looper.java:136)
> E/EventChannel#channel/to/tdlib/receive( 6459): at android.app.ActivityThread.main(ActivityThread.java:6077)
> E/EventChannel#channel/to/tdlib/receive( 6459): at java.lang.reflect.Method.invoke(Native Method)
> E/EventChannel#channel/to/tdlib/receive( 6459): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
> E/EventChannel#channel/to/tdlib/receive( 6459): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
> E/EventChannel#channel/to/tdlib/receive( 6459): Failed to close existing event stream
> E/EventChannel#channel/to/tdlib/receive( 6459): java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Number.longValue()' on a null object reference
> E/EventChannel#channel/to/tdlib/receive( 6459): at org.naji.td.tdlib.TdlibPlugin.onCancel(TdlibPlugin.java:175)
> E/EventChannel#channel/to/tdlib/receive( 6459): at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:182)
> E/EventChannel#channel/to/tdlib/receive( 6459): at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:167)
> E/EventChannel#channel/to/tdlib/receive( 6459): at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
> E/EventChannel#channel/to/tdlib/receive( 6459): at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
> E/EventChannel#channel/to/tdlib/receive( 6459): at android.os.MessageQueue.nativePollOnce(Native Method)
> E/EventChannel#channel/to/tdlib/receive( 6459): at android.os.MessageQueue.next(MessageQueue.java:323)
> E/EventChannel#channel/to/tdlib/receive( 6459): at android.os.Looper.loop(Looper.java:136)
> E/EventChannel#channel/to/tdlib/receive( 6459): at android.app.ActivityThread.main(ActivityThread.java:6077)
> E/EventChannel#channel/to/tdlib/receive( 6459): at java.lang.reflect.Method.invoke(Native Method)
> E/EventChannel#channel/to/tdlib/receive( 6459): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
> E/EventChannel#channel/to/tdlib/receive( 6459): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

This happens when i try to send a method using the send function in the example.

**Comment by i-Naji** [comment]
please update to last version.

**Comment by alazarLaz** [comment]
flutter or java?

**Comment by alazarLaz** [comment]
java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)

and

[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_US.UTF-8)

this are my flutter and java versions, maybe give me yours so it would match

**Comment by i-Naji** [comment]
last version of plugin

**Comment by alazarLaz** [comment]
![Screenshot from 2020-11-28 08-58-15](https://user-images.githubusercontent.com/66739752/100494989-15597780-3158-11eb-9dbb-5ce0b48efbd6.png)



tdlib: ^1.3.0 
right?

if it is it is not working on it, maybe i have to setup flutter again.

**Comment by i-Naji** [comment]
1.4.0 is the last version

**Comment by alazarLaz** [comment]
it still is not working, maybe you guys could give me your flutter and jdk version so i could set it up on it.

**Comment by alazarLaz** [comment]
> it still is not working, maybe you guys could give me your flutter and jdk version so i could set it up on it.

i have finished the authorization flow from your example, but after that on the home screen any send function results in the above error.
