### ISSUE TITLE
can you please update the example?

### ISSUE THREAD

**Issue by selvasoft** [i-Naji/tdlib#3]
Can you please update the example to make request functions and receive the updates of sent functions?

**Comment by jacklee768** [comment]
> Can you please update the example to make request functions and receive the updates of sent functions?

我也有相同的问题

**Comment by jacklee768** [comment]
> Can you please update the example to make request functions and receive the updates of sent functions?


I also have the same problem.

**Comment by YaredTaddese** [comment]
Yes please, just simple example how to get started sending a message and getting an update.
