### ISSUE TITLE
get all chats?

### ISSUE THREAD

**Issue by deckvv** [i-Naji/tdlib#30]
how to get all chats? i dont understand how to call method

**Comment by Onionus007** [comment]
Hey, I also have a problem with the method, you ever figured it out?

**Comment by FaKenKoala** [comment]
Check the comments in GetChats class definition，you should set ‘offsetOrder’ value to 9223372036854775807 (2 << 63 -1).

**Comment by i-Naji** [comment]
[Getting the lists of chats](https://core.telegram.org/tdlib/getting-started#getting-the-lists-of-chats)
