### ISSUE TITLE
How to persist user session to not need to sign in again every time a hot reload is done?

### ISSUE THREAD

**Issue by ARTester403** [i-Naji/tdlib#36]
Does anyone know of a way to persist the user's session such as saving the session and loading it back into the app without the user needing to enter their phone number and go through the sign in process again?

The issue I have is that, every time I hot reload in Flutter, I need to go through that sign in process again whenever I change my code. There is a python library called Telethon which lets you save the session, but I was wondering if you could do that with this library.

I've tried to read the source code to find out if there is anything I could use, but I cannot find anything so would really appreciate it if someone could guide me on how I can persist the user's session.

**Comment by i-Naji** [comment]
TDLib stores session data in the database as you address that in `SetTdlibParameters` method with `databaseDirectory`, while using the **same address** TDLib will use the same session data.
