### ISSUE TITLE
Can we Stream Telegram Videos ?

### ISSUE THREAD

**Issue by rohitsangwan01** [i-Naji/tdlib#42]
hey , Great package , can we stream telegram videos , or if possible can we get a callback or something for download or upload progress ??

**Comment by i-Naji** [comment]
Hi, yes you can
for example use [DownloadFile](https://pub.dev/documentation/tdlib/latest/td_api/DownloadFile-class.html) method then you will receive [UpdateFile](https://pub.dev/documentation/tdlib/latest/td_api/UpdateFile/UpdateFile.html) events of downloading progress.
