### ISSUE TITLE
Wrong auto generated file

### ISSUE THREAD

**Issue by denisnadey** [i-Naji/tdlib#43]
The installation of the package creates a file 
generated_plugin_registrant.dart
with wrong paths (which makes it impossible to start the project in any way) also please fix the example for ios 
please If possible, contact me on telegram @denisdandy

**Comment by Kraigo** [comment]
the same issue

**Comment by danhdevelop** [comment]
lib/generated_plugin_registrant.dart:45:3: Error: Undefined name 'TdWebPlugin'.
  TdWebPlugin.registerWith(registrar);

The same issue with web. Android is fine

**Comment by i-Naji** [comment]
Fixed in v1.6.0
