### ISSUE TITLE
Version 1.5.9 crash with "type 'Null' is not a subtype of type 'String' in type cast"

### ISSUE THREAD

**Issue by STmihan** [i-Naji/tdlib#49]
After updating tdlib to 1.5.9 it crashes with the error:
```
Oops; flutter has exited unexpectedly: "type 'Null' is not a subtype of type 'String' in type cast".
A crash report has been written to C:\Projects\telegramnews\flutter_03.log.
```
log:
[flutter_03.log](https://github.com/i-Naji/tdlib/files/10716282/flutter_03.log)

tdlib version is `tdlib: 1.5.9+1`
Version 1.5.0 works correctly with no crashes

**Comment by i-Naji** [comment]
update the plugin and enjoy `tdlib: 1.8.15`
