### ISSUE TITLE
I can't execute the example

### ISSUE THREAD

**Issue by konstantinullrich** [i-Naji/tdlib#5]
A problem occurred configuring project ':tdlib'.
> NDK not configured. 
  Download it with SDK manager.

**Comment by jacklee768** [comment]
> A problem occurred configuring project ':tdlib'.
> 
> > NDK not configured.
> > Download it with SDK manager.

You need to install the NDK and configure it in the local.properties file in your project, like this:
`
sdk.dir=C:\\Users\\MT-PC\\AppData\\Local\\Android\\Sdk
flutter.sdk=C:\\flutter
// add this
ndk.dir=C\:\\Users\\MT-PC\\AppData\\Local\\Android\\Sdk\\ndk\\20.0.5594570
`

**Comment by jacklee768** [comment]
> A problem occurred configuring project ':tdlib'.
> 
> > NDK not configured.
> > Download it with SDK manager.

You need to install the NDK and configure it in the local.properties file in your project, like this:
`ndk.dir=C\:\\Users\\MT-PC\\AppData\\Local\\Android\\Sdk\\ndk\\20.0.5594570`
