### ISSUE TITLE
The plugin `tdlib` is missing the required field `fileName` in pubspec.yaml

### ISSUE THREAD

**Issue by kullhy** [i-Naji/tdlib#52]
i upgrade Dart to 3.0, and i got this error
The plugin `tdlib` is missing the required field `fileName` in pubspec.yaml

**Comment by emmersmacks** [comment]
I also have this error did you find a solution?

**Comment by michele-grifa** [comment]
I have the same problem on a newly created flutter project with Android Studio

**Comment by emmersmacks** [comment]
> I have the same problem on a newly created flutter project with Android Studio

If you are creating a new application, then I advise you to switch to this solution: 
https://github.com/ivk1800/tdlib-dart
It works fine for me.

**Comment by MetaMmodern** [comment]
@emmersmacks the advised solution has no web support(yet).

**Comment by i-Naji** [comment]
Version 1.6.0 is compatible with Dart v3 :)
