### ISSUE TITLE
TDlib-IOS global symbols not found

### ISSUE THREAD

**Issue by tanguoyang** [i-Naji/tdlib#53]
Hello! I am trying to add tdlib support for ios, but the link below in 2. no longer exists. I have tried many other methods described online but cant seem to get it to work. Could someone help me with step 2?

for IOS and macOS support:
1. Build tdlib-json by this [instruction](https://github.com/tdlib/td/tree/master/example/ios)
2. [Add compiled file to linked libraries](https://docs.flutter.dev/development/platform-integration/c-interop#compiled-dynamic-library) and use it's name for initialization

**Comment by i-Naji** [comment]
I will update the link.

**Comment by i-Naji** [comment]
https://docs.flutter.dev/platform-integration/macos/c-interop#compiled-dynamic-library-macos
